name: build
# When the 'permissions' key is specified, unspecified permission scopes (e.g.,
# actions, checks, etc.) are set to no access (none).
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly (* is a special character in YAML, so quote the string)
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      # When git-ref is empty, HEAD will be checked out.
      git-ref:
        description: Optional git ref (branch, tag, or full SHA)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # When the ref is empty, HEAD will be checked out.
        ref: ${{ github.event.inputs.git-ref }}

    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install lua-check neovim

    - name: Check Help Tags
      run: |
        # Check if the help tags file should be updated
        nvim -c 'helptags doc/' -c quit
        test -z "$(git status --porcelain doc/)"

    - name: Luacheck
      run: luacheck .

    - name: Tests
      run: |
        mkdir -p ~/.local/share/nvim/site/pack/plugins/start/
        ln -s "$PWD" ~/.local/share/nvim/site/pack/plugins/start/
        tests/run.py
